---
abstract: "Perl extension to OpenSSL's PKCS10 API."
author:
  - 'JoNO <jonozzz@yahoo.com>'
build_requires:
  Crypt::OpenSSL::Guess: '0.11'
  Crypt::OpenSSL::RSA: '0'
  Test::More: '0'
configure_requires:
  Crypt::OpenSSL::Guess: '0.11'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-OpenSSL-PKCS10
provides: {}
recommends:
  Crypt::OpenSSL::Bignum: '0'
requires:
  Crypt::OpenSSL::RSA: '0'
  perl: '5.008'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Crypt-OpenSSL-PKCS10
  homepage: http://search.cpan.org/dist/Crypt-OpenSSL-PKCS10/
  repository: git://github.com/perl-net-saml2/perl-Crypt-OpenSSL-PKCS10.git
version: '0.22'
x_generated_by_perl: v5.36.1
x_maintainers:
  - 'Timothy Legge <timlegge@cpan.org>'
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
